name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest test_app.py

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t flask-cicd-demo .
          docker tag flask-cicd-demo ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest
          
